// L-04 — the blog articles' <picture> blocks are honest.
//
// The four article images ship as AVIF + WebP + JPEG in four widths, generated by
// assets-src/blog-images.py and referenced by hand in four sibling HTML files (no build
// step, no templating — the block is duplicated on purpose, like everything else on this
// site). A typo in one of those blocks is a 404 the browser swallows silently: it just
// falls back to a worse candidate, and nothing anywhere goes red. This suite is what goes
// red. Zero dependencies — node:test + node:fs, same lane as the Worker tests.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const PUBLIC = join(ROOT, 'public');
const BLOG = join(PUBLIC, 'blog');

const articles = readdirSync(BLOG)
  .filter((f) => f.endsWith('.html'))
  .map((f) => ({ file: f, html: readFileSync(join(BLOG, f), 'utf8') }));

// WIDTHS as the generator declares it — the HTML has to name exactly these.
const generatorWidths = (() => {
  const src = readFileSync(join(ROOT, 'assets-src', 'blog-images.py'), 'utf8');
  const m = src.match(/^WIDTHS = \(([^)]*)\)/m);
  assert.ok(m, 'assets-src/blog-images.py must declare `WIDTHS = (...)` at column 0');
  return m[1].split(',').map((s) => Number(s.trim())).filter(Boolean);
})();

const pictures = (html) => [...html.matchAll(/<picture>([\s\S]*?)<\/picture>/g)].map((m) => m[1]);
const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1];
const srcsetWidths = (srcset) =>
  srcset.split(',').map((c) => c.trim().split(/\s+/)).map(([url, d]) => ({ url, width: Number(d?.replace(/w$/, '')) }));

const withPictures = articles.filter((a) => pictures(a.html).length > 0);

test('the four illustrated articles carry one <picture> per figure — no bare JPEG left', () => {
  assert.equal(withPictures.length, 4, 'four articles are illustrated (the other three and the index have no image)');
  for (const { file, html } of articles) {
    const figures = (html.match(/<figure class="post-img">/g) ?? []).length;
    assert.equal(pictures(html).length, figures, `${file}: every .post-img figure is a <picture>`);
    assert.doesNotMatch(html, /<img src="\/blog\/img\/[a-z-]+\.jpg"/, `${file}: an <img> still points at a 1600 px master`);
  }
});

test('every file a blog <picture> names exists under public/', () => {
  for (const { file, html } of withPictures) {
    for (const pic of pictures(html)) {
      const urls = [
        ...[...pic.matchAll(/srcset="([^"]*)"/g)].flatMap((m) => srcsetWidths(m[1]).map((e) => e.url)),
        attr(pic.match(/<img[^>]*>/)[0], 'src'),
      ];
      assert.ok(urls.length >= 3 * generatorWidths.length + 1, `${file}: three srcsets plus a src`);
      for (const url of urls) {
        assert.ok(url.startsWith('/blog/img/'), `${file}: ${url} lives under /blog/img/`);
        assert.ok(existsSync(join(PUBLIC, url)), `${file}: ${url} is not on disk — re-run assets-src/blog-images.py`);
      }
    }
  }
});

test('AVIF, WebP and JPEG name the same widths, in the same order as the generator, with one `sizes`', () => {
  for (const { file, html } of withPictures) {
    for (const pic of pictures(html)) {
      const sources = [...pic.matchAll(/<source[^>]*>/g)].map((m) => m[0]);
      const img = pic.match(/<img[^>]*>/)[0];
      assert.deepEqual(sources.map((s) => attr(s, 'type')), ['image/avif', 'image/webp'], `${file}: AVIF first, then WebP`);
      const sizes = new Set([...sources, img].map((t) => attr(t, 'sizes')));
      assert.equal(sizes.size, 1, `${file}: every candidate list shares one sizes attribute`);
      assert.ok([...sizes][0], `${file}: sizes is present — without it the browser assumes 100vw`);
      for (const tag of [...sources, img]) {
        const entries = srcsetWidths(attr(tag, 'srcset'));
        assert.deepEqual(entries.map((e) => e.width), generatorWidths, `${file}: ${attr(tag, 'type') ?? 'img'} widths match WIDTHS in blog-images.py`);
        for (const { url, width } of entries) {
          assert.ok(url.endsWith(`-${width}.${url.split('.').pop()}`), `${file}: ${url} is the ${width} px file`);
        }
      }
      assert.equal(attr(img, 'loading'), 'lazy', `${file}: the figure sits mid-article`);
      assert.equal(attr(img, 'decoding'), 'async', `${file}: decode off the main thread, like the home screenshots`);
      assert.ok(attr(img, 'alt'), `${file}: alt survived the rewrite`);
      assert.equal(Number(attr(img, 'width')) * 9, Number(attr(img, 'height')) * 16, `${file}: width/height hint is 16:9, the crop the CSS shows`);
    }
  }
});

test('the article CSS lets aspect-ratio win over the height attribute', () => {
  // The `height` attribute on <img> is a presentational hint for the CSS `height` property, and
  // `aspect-ratio` only applies while height is auto. Without `height:auto` in the rule, every
  // article image rendered 675 px tall whatever its width — a near-square crop on desktop and a
  // portrait one on a phone — while the stylesheet said 16:9 (measured on production, 14/09/2026).
  for (const { file, html } of withPictures) {
    const rule = html.match(/\.post-img img\{([^}]*)\}/)?.[1];
    assert.ok(rule, `${file}: has the .post-img img rule`);
    assert.match(rule, /(^|;)height:auto(;|$)/, `${file}: .post-img img sets height:auto`);
    assert.match(rule, /aspect-ratio:16\/9/, `${file}: .post-img img keeps aspect-ratio:16/9`);
  }
});

test('the og:image / twitter:image / JSON-LD image stay on the untouched 1600 px master', () => {
  for (const { file, html } of withPictures) {
    const og = html.match(/property="og:image" content="([^"]*)"/)?.[1];
    assert.ok(og, `${file}: has an og:image`);
    const path = og.replace(/^https:\/\/entrelares\.app/, '');
    assert.match(path, /^\/blog\/img\/[a-z-]+\.jpg$/, `${file}: og:image is a bare master (social scrapers want a JPEG at a URL that never moves)`);
    assert.ok(existsSync(join(PUBLIC, path)), `${file}: ${path} exists`);
    assert.equal(html.match(/name="twitter:image" content="([^"]*)"/)?.[1], og, `${file}: twitter:image is the same file`);
    assert.ok(html.includes(`"image": "${og}"`), `${file}: JSON-LD image is the same file`);
  }
});
