#!/usr/bin/env python3
"""F-54 — derive the site icons from the official Entrelares brand artwork.

The MASTER is assets-src/brand-emblema.png (1380x752): the 3D emblem the owner
approved — two interlocked house-rings (sage fabric + terracotta wood) on a white
squircle plaque, children lighting a flame at the junction, embossed houses,
"ENTRELARES" engraved and the tagline "DUAS CASAS, UMA MESMA INFANCIA" on the
plaque. Generated by an external AI tool; there is no vector source — ask for a
new generation to change the art, then re-run this script.

The plaque sits at (352,62)-(1046,690); the icon is a 730x730 crop centred on it:
(334,11)-(1064,741).

Usage (needs Pillow):  python3 assets-src/brand-icons.py

Outputs:  public/favicon.png (96)   public/icon-192.png   public/icon-512.png

The app repo carries its own copy of the master and of this script
(store/brand-emblema.png + store/brand-icons.py, which also builds the maskable
variants) — regenerate BOTH repos when the artwork changes.
"""
from PIL import Image
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CROP = (334, 11, 1064, 741)  # 730x730 square centred on the plaque

src = Image.open(ROOT / "assets-src" / "brand-emblema.png").convert("RGB")
square = src.crop(CROP)

for size, name in ((96, "favicon.png"), (192, "icon-192.png"), (512, "icon-512.png")):
    square.resize((size, size), Image.LANCZOS).save(ROOT / "public" / name, optimize=True)
    print("ok", name)
